### ISSUE TITLE
COVID-19 treatment inherited axioms

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#12]
`COVID-19 treatment` has the inherited axioms:
```
'has prototype' only process
'in similarity relationship with' only occurrent
```
I'm guessing the MERIOT process pulled these in, but I don't think we need them. What work are they doing? Also, we probably do need the axiom `part_of only occurrent`.

**Comment by yongqunh** [comment]
It appears that for each process, it has the axiom: 
'has prototype' only process

for each occurrent, it has the axiom:
'in similarity relationship with' only occurrent

They appear not in the class only BFO:
http://purl.obolibrary.org/obo/BFO_0000003
http://purl.obolibrary.org/obo/BFO_0000015 

They may be obtained from another ontology (or ontologies) that uses a previous version of BFO.

**Comment by yongqunh** [comment]
In our updated merged OWL file, I have manually removed all these relations to make the BFO terms basically class only. Then these relations are gone. 
I think I will also do the same in the later updates.  
Thanks.

**Comment by wdduncan** [comment]
Thanks @yongqunh !
I'm wondering if we can write a script to to remove the axioms. That way the removal is automated.

**Comment by yongqunh** [comment]
That's good point.  It did not take me too much time to do it. However, I think you are right. We may write a script for it. 
Another way is to check the source ontologies and ensure they are BFO class only; if not, we may contact them to change.  
Thanks.
