### ISSUE TITLE
Make COVID-19 treatment a defined class

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#13]
We may want to consider making COVID-19 treatment a defined class. Something like:
```
COVID-19 treatment Equivalent To treatment for some COVID-19 disease process
```
However, the definition for `treatment for` states the relation can only hold between a drug and disease process, and not all treatments necessarily involve drugs (e.g., respirators).

**Comment by yongqunh** [comment]
Great. I have added this equivalent definition. Meanwhile, we have updated the relation 'treatment for' to make it cover other matierial entities such as respirators. I think this issue is then resolved, and I will close the issue for now.

**Comment by linikujp** [comment]
What dose Respirator treat for? Is it defined in the CIDO?
