### ISSUE TITLE
is 'coronaviral process to host' a 'bodily process'?

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#15]
Currently, `coronaviral process to host` is as sibling of `bodily process`. Although there is not a definition for `bodily process` (which is annoying), I suppose a `bodily process` is meant to be process that occurs within the subject's body.  If so, shouldn't `coronaviral process to host` be a subclass of `bodily process`?

cc @sivaramarabandi @yongqunh @linikujp

**Comment by yongqunh** [comment]
Yes. I agree. This is added.
