### ISSUE TITLE
disease process vs disease course

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#16]
The ontology uses the ICDO class `disease process` as super class of `coronavirus infectious disease (process)`. However, the ontology also includes OGMS' `disease course` class. We isn't `coronavirus infectious disease (process)` a child of `disease course`? In other words, what is the appropriate distinction between `disease process` and `disease course` that is pertinent to classifying`coronavirus infectious disease (process)`. 

FWIW, I don't OGMS is clear about its distinction between a `bodily process` and a `disease course` either. But, if we find the distinction here confusing, I think we should not include one of the classes.

cc @yongqunh @sivaramarabandi @linikujp

**Comment by yongqunh** [comment]
OGMS' disease course class definition:
"The totality of all processes through which a given disease instance is realized."

The totality defined in the 'disease course' means that the survival of the pathogen (e.g., some virus, bacterium, or parasite) outside a human body such as in insect, animal host such as bat, or air may also be part of the disease course.   

The OGMS term 'bodily process' is in parallel with the OGMS' disease course.
The disease process is a subclass of OGMS's pathological bodily process, which is a subclass of OGMS term 'bodily process'.

**Comment by yongqunh** [comment]
Yes. I think that disease process is a part of disease course

**Comment by yongqunh** [comment]
I think this issue is solved. Feel free to reopen if more disscussion is needed. Thanks.
