### ISSUE TITLE
There is a problem with the class "drug role" in CIDO

### ISSUE THREAD

**Issue by xiaoyuchn** [CIDO-ontology/cido#21]
In CIDO, the term "drug role" comes from the term "drug" in CHEBI, indicating that the term "drug" has been modified, and this operation does not conform to the principles of OBO Foundry ontology construction. Why should it be revised? Hope to get an answer. Thanks.

**Comment by yongqunh** [comment]
There is another term in CIDO called 'drug'. therefore, we decided to change the CHBI term label. The ChEBI drug term is located under role so it is indeed drug role.
