### ISSUE TITLE
Duplicate classes for PR_P0DTC4

### ISSUE THREAD

**Issue by janelomax** [CIDO-ontology/cido#27]
You seem to have duplicate classes for _envelope small membrane protein_:

[http://purl.obolibrary.org/obo/PR_P0DTC4](http://purl.obolibrary.org/obo/PR_P0DTC4)
[http://purl.obolibrary.org/obo/vo/ontorat/PR_P0DTC4](http://purl.obolibrary.org/obo/vo/ontorat/PR_P0DTC4)

thanks

**Comment by yongqunh** [comment]
It appears that this issue has been resolved. So I am going to close this. 
Thanks.

**Comment by janelomax** [comment]
Still in Version: 1.0.337

![Screenshot 2022-12-20 at 13 24 04](https://user-images.githubusercontent.com/6639811/208677414-40ea5dbd-9c16-4efb-84b7-d9750f989dda.png)
