### ISSUE TITLE
Two "part_of" object properties

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#31]
There two object properties with the label `part_of`:
 - http://purl.obolibrary.org/obo/BFO_0000050 which is `transitive` and `reflexive`
 - http://purl.obolibrary.org/obo/so#part_of which is only `transitive`

Are both needed? Having both relations may make the ontology more confusing for editors.

cc @yongqunh @linikujp @sivaramarabandi

**Comment by linikujp** [comment]
It seems that the so#part_of was manually asserted in CIDO. It should be replaced by the BFO_0000050

**Comment by Huffmaar** [comment]
'part_of' has been deprecated and replaced with the proper BFO term 'part of'
