### ISSUE TITLE
two develops from object properties in the ontology

### ISSUE THREAD

**Issue by wdduncan** [CIDO-ontology/cido#32]
There are two develops from object properties in the ontology:
- "develops from" (no underscore) `http://purl.obolibrary.org/obo/RO_0001000`
- "develops_from" (with an underscore) `http://purl.obolibrary.org/obo/RO_0002202`

Both are used within the ontology, so I am not sure what the correct approach is here. But, it may cause confusion for ontology editors.

cc @yongqunh @sivaramarabandi @linikujp

**Comment by wdduncan** [comment]
When I look at the `2021-08-04` of RO, only `develops from` (no underscore, `http://purl.obolibrary.org/obo/RO_0001000`) is listed.

We can set an equivalence axiom between the two (i.e.,`develops from` eqiv property `develops_from`) which may fix the problem. But we need to test.

**Comment by linikujp** [comment]
This is fixed. No more develops_from (RO:0002202) in the owl file.
