### ISSUE TITLE
Question about cido and cido-base

### ISSUE THREAD

**Issue by xiaoyuchn** [CIDO-ontology/cido#34]
I found that the difference between the file cido and cido-base is whether to display "import". I would like to ask how this is done. I want to learn to integrate the ontology that is reused as a whole. thanks.

**Comment by yongqunh** [comment]
You can use our merged cido version which does not have the seperate imported files. 
However, we don't always make the merged cido version. 
To open the cido-base in a correct way, the best thing to do is to download the GitHub repository as a whole and open the cido-base there bacause it needs to import the other owl files with the file directory structure.

**Comment by xiaoyuchn** [comment]
Could you tell me what tool was used to build the merged cido? I am curious about this.

**Comment by yongqunh** [comment]
I used Protege OWL editor, which has a function to merge. I think you can use some other tools for it as well. ROBOT may do the trick.

**Comment by xiaoyuchn** [comment]
Thank you for your prompt reply, I will try to use these tools.

**Comment by yongqunh** [comment]
Great. I will then close the issue. Let us know if you need more support. Best.
