### ISSUE TITLE
Some protein sequences and other terms become "obsolete"

### ISSUE THREAD

**Issue by linikujp** [CIDO-ontology/cido#35]
Please double check.
![image](https://user-images.githubusercontent.com/8712765/129734335-d24c0a15-c541-4f9f-b9a7-376ed7245df8.png)

**Comment by wdduncan** [comment]
If the term are in fact obsoleted, then the `owl:deprecated`(annotation property) needs to be marked as `true`.
![image](https://user-images.githubusercontent.com/3186638/129734602-e1e25fb9-3a99-4911-b099-10fe97031336.png)

**Comment by Huffmaar** [comment]
Added owl:deprecated as True for all obsolete terms
